import type { Manifest } from '../manifest/types.ts';
import { materialIdList } from '../manifest/types.ts';
import type { PresetState } from '../state/presetLogic.ts';

/**
 * VRChat/Unity recreation config: a human- and machine-readable summary of
 * the current preset (toggle choices as labels, sliders as percents, texture
 * set, region colors as hex). Pure/DOM-free — Node-tested.
 */

export interface VrcToggleSelection {
  id: string;
  label: string;
}

export interface VrcToggleGroup {
  id: string;
  label: string;
  mode: 'exclusive' | 'independent';
  /** exclusive: exactly one entry; independent: the enabled options (may be empty). */
  selected: VrcToggleSelection[];
}

export interface VrcSlider {
  id: string;
  label: string;
  group: string;
  value: number;
  min: number;
  max: number;
  /** 0–100, position of value within [min, max]. */
  percent: number;
}

export interface VrcColorRegion {
  id: string;
  label: string;
  /** Logical material id(s), joined with ", " when the region spans several. */
  material: string;
  /** "#rrggbb". */
  color: string;
}

export interface VrcEmissiveRegion extends VrcColorRegion {
  intensity: number;
}

export interface VrcConfig {
  schemaVersion: 1;
  generator: string;
  pack: { id: string; name: string };
  toggles: VrcToggleGroup[];
  sliders: VrcSlider[];
  textureSet: { id: string; label: string } | null;
  colors: VrcColorRegion[];
  emissive: VrcEmissiveRegion[];
}

/** Resolve the preset's ids against the manifest into labels/percents/hex. */
export function buildVrcConfig(manifest: Manifest, preset: PresetState): VrcConfig {
  const toggles: VrcToggleGroup[] = manifest.toggleGroups.map((group) => {
    const selection = preset.toggles[group.id];
    const selected =
      group.mode === 'exclusive'
        ? group.options.filter((o) => o.id === selection)
        : group.options.filter((o) => Array.isArray(selection) && selection.includes(o.id));
    return {
      id: group.id,
      label: group.label,
      mode: group.mode,
      selected: selected.map((o) => ({ id: o.id, label: o.label })),
    };
  });

  const sliders: VrcSlider[] = manifest.sliders.map((s) => {
    const value = preset.sliders[s.id] ?? s.default;
    const percent = s.max > s.min ? Math.round(((value - s.min) / (s.max - s.min)) * 100) : 0;
    return { id: s.id, label: s.label, group: s.group, value, min: s.min, max: s.max, percent };
  });

  const set =
    manifest.textureSets.find((s) => s.id === preset.textureSet) ?? manifest.textureSets[0] ?? null;

  return {
    schemaVersion: 1,
    generator: 'SynthCreator3D',
    pack: { id: manifest.id, name: manifest.name },
    toggles,
    sliders,
    textureSet: set ? { id: set.id, label: set.label } : null,
    colors: manifest.colorRegions.map((r) => ({
      id: r.id,
      label: r.label,
      material: materialIdList(r.material).join(', '),
      color: preset.colors[r.id] ?? r.defaultColor,
    })),
    emissive: manifest.emissiveRegions.map((r) => ({
      id: r.id,
      label: r.label,
      material: materialIdList(r.material).join(', '),
      color: preset.emissive[r.id] ?? r.defaultColor,
      intensity: r.intensity,
    })),
  };
}

/** Render the config as a Markdown document meant for Unity-side recreation. */
export function renderVrcConfigMarkdown(config: VrcConfig): string {
  const lines: string[] = [];
  lines.push(`# VRChat avatar config — ${config.pack.name}`);
  lines.push('');
  lines.push(`Pack: \`${config.pack.id}\` · Generated by ${config.generator} (schema v${config.schemaVersion})`);
  lines.push('');
  lines.push('## Parts (toggles)');
  for (const group of config.toggles) {
    const value =
      group.selected.length > 0 ? group.selected.map((s) => s.label).join(', ') : '(none)';
    lines.push(`- ${group.label}: ${value}`);
  }
  lines.push('');
  lines.push('## Morph sliders');
  for (const s of config.sliders) {
    lines.push(`- ${s.group} / ${s.label}: ${s.percent}% (${s.value.toFixed(2)} in [${s.min}, ${s.max}])`);
  }
  lines.push('');
  lines.push('## Texture set');
  lines.push(`- ${config.textureSet ? config.textureSet.label : '(none)'}`);
  lines.push('');
  lines.push('## Color regions');
  for (const c of config.colors) {
    lines.push(`- ${c.label} [${c.material}]: ${c.color}`);
  }
  lines.push('');
  lines.push('## Emissive regions');
  for (const e of config.emissive) {
    lines.push(`- ${e.label} [${e.material}]: ${e.color} (intensity ${e.intensity})`);
  }
  lines.push('');
  lines.push('## Unity recreation notes');
  lines.push('- Toggles map to GameObject active states (drive them from an FX-layer parameter).');
  lines.push('- Sliders map to blendshape weights; the percent is within the slider’s min–max range.');
  lines.push('- Color regions tint the albedo where the region mask is white; emissive regions drive emission color × mask.');
  lines.push('');
  return lines.join('\n');
}
